# Generated by Django 4.2.20 on 2025-04-29 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartnerRequest',
        ),
    ]
