# Generated by Django 5.1.7 on 2025-03-24 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_pub_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ans',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
