# Generated by Django 5.1.7 on 2025-03-25 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='img',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
