# Generated by Django 4.2.20 on 2025-03-25 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_listing_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Pending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u1', models.IntegerField(blank=True, null=True)),
                ('u2', models.IntegerField(blank=True, null=True)),
                ('u3', models.IntegerField(blank=True, null=True)),
                ('u4', models.IntegerField(blank=True, null=True)),
                ('lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
            ],
        ),
    ]
