# Generated by Django 4.2.20 on 2025-04-13 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_alter_listing_pub_date_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending',
            name='lamount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pending',
            name='oamount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pending',
            name='oid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='offered', to='listings.listing'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pending',
            name='lid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listed', to='listings.listing'),
        ),
    ]
