# Generated by Django 4.2.20 on 2025-04-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending',
            name='partner_receiving',
            field=models.CharField(default='Myself', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pending',
            name='partner_sending',
            field=models.CharField(default='Myself', max_length=50),
            preserve_default=False,
        ),
    ]
