# Generated by Django 4.2.20 on 2025-04-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_pending_partner_receiving_pending_partner_sending'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
