# Generated by Django 4.2.20 on 2025-04-17 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0013_alter_profile_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending',
            name='lastsent',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='listing',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
