# Generated by Django 4.2.20 on 2025-04-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_pending_lastsent_alter_listing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending',
            name='partner_receiving',
            field=models.CharField(choices=[('Myself', 'Myself'), ('My Partner', 'My Partner')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pending',
            name='partner_sending',
            field=models.CharField(choices=[('Myself', 'Myself'), ('My Partner', 'My Partner')], max_length=50),
        ),
    ]
