# Generated by Django 4.2.20 on 2025-04-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_alter_pending_partner_receiving_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('inputuser', models.IntegerField()),
            ],
        ),
    ]
