# Generated by Django 4.2.20 on 2025-04-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_partnerrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerrequest',
            name='inputuser',
            field=models.IntegerField(null=True),
        ),
    ]
