# Generated by Django 4.2.20 on 2025-04-29 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_pending_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerrequest',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
