# Generated by Django 4.2.20 on 2025-04-30 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_alter_partnerrequest_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accepted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lamount', models.IntegerField()),
                ('oamount', models.IntegerField()),
                ('partner_receiving', models.CharField(choices=[('Myself', 'Myself'), ('My Partner', 'My Partner')], max_length=50)),
                ('partner_sending', models.CharField(choices=[('Myself', 'Myself'), ('My Partner', 'My Partner')], max_length=50)),
                ('u1', models.IntegerField(blank=True, null=True)),
                ('u2', models.IntegerField(blank=True, null=True)),
                ('u3', models.IntegerField(blank=True, null=True)),
                ('u4', models.IntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_listed', to='listings.listing')),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_offered', to='listings.listing')),
            ],
        ),
    ]
