# Generated by Django 4.2.20 on 2025-04-30 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_accepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accepted',
            old_name='partner_receiving',
            new_name='offerpartner_receiving',
        ),
        migrations.RenameField(
            model_name='accepted',
            old_name='partner_sending',
            new_name='postpartner_receiving',
        ),
        migrations.RenameField(
            model_name='pending',
            old_name='partner_receiving',
            new_name='offerpartner_receiving',
        ),
        migrations.RenameField(
            model_name='pending',
            old_name='partner_sending',
            new_name='postpartner_receiving',
        ),
    ]
