# Generated by Django 4.2.20 on 2025-04-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_rename_partner_receiving_accepted_offerpartner_receiving_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted',
            name='lamount',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
        migrations.AlterField(
            model_name='accepted',
            name='oamount',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pending',
            name='lamount',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pending',
            name='oamount',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
    ]
