# Generated by Django 4.2.20 on 2025-04-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_alter_accepted_lamount_alter_accepted_oamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_alive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_chilled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_fragile',
            field=models.BooleanField(default=False),
        ),
    ]
