# Generated by Django 4.2.20 on 2025-05-01 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0026_listing_is_alive_listing_is_chilled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accepted',
            name='hashkey',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='accepted',
            name='verified',
            field=models.IntegerField(default=0),
        ),
    ]
